M48
; DRILL file {KiCad 7.0.2} date Wed Jun 21 11:38:31 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-06-21T11:38:31+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.720
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C3.250
%
G90
G05
T1
X162.4Y-63.85
X162.4Y-65.55
X242.1Y-56.7
X243.8Y-56.7
T2
X237.0Y-119.85
X251.0Y-119.85
T3
X164.0Y-58.3
X164.0Y-137.9
X249.3Y-58.15
T4
X170.28Y-117.9
X170.28Y-129.33
T0
M30
